import java.util.*;
import java.util.Random;
public class Numbergame
{
    public static void main(String[]args)
    {
        //calling generateRandom method
       generateRandom();
       
   
    
    }


    public static void generateRandom()
    {
        //creating an object of random class
        Random randNum = new Random();
        //creating a randomnum varibale which can store random numbers generated by generate random method
        int randomnum = randNum.nextInt(101);
        guess(randomnum);


    }
    public static void guess(int randomnum)
    {
       Scanner o = new Scanner(System.in);
       System.out.println(" ");
       System.out.println("Number guessing game...u have four chance to guess the correct number");
       
      int guess;
       int tries=0;
       while(tries<4){
        tries++;
        System.out.println("enter a number between 1-100");
       guess=o.nextInt();
       
       if(guess!=randomnum) 
       {
        
        
         if(guess<=0 || guess>100)
         {

            System.out.println("enter a number within a range of 1-100 ");
           
         }
         else{
            
            if(guess>randomnum)
            {
                System.out.println("wrong guess...too high");
            }else {
                System.out.println("wrong guess...too low");
            }

         }

       }
       else 
              {
                System.out.println(" guessed correctly....you won the game");
                System.out.println("the no of tries are"+ tries);
          
                
              }
         



       }
                  
       System.out.println("press 1 if u want to play again or press 0 for exit");
       Scanner p = new Scanner(System.in);
       int choice = p.nextInt();
       if(choice == 1)
                   {
                      generateRandom();
                   }
                  else
                  {
                    return;
                  }
    }
   
     

}
